### GET ALL Administradores
GET http://localhost:3000/api/administradores

### POST Crear un Administrador
# @name createAdministrador
POST http://localhost:3000/api/administradores
Content-Type: application/json

{
  "nombre": "Cesar",
  "apellido": "Ramírez",
  "telefono": "3415076254",
  "usuario": "cesar_ramirez",
  "password": "9deJulio2325",
  "email": "tintapapelymusica@gmail.com"
}

### ID del Administrador creado
@id = {{createAdministrador.response.body.data.id}}

### GET Un Administrador por ID
GET http://localhost:3000/api/administradores/{{id}}

### PATCH Actualizar un Administrador
PATCH http://localhost:3000/api/administradores/{{id}}
Content-Type: application/json

{
  "nombre": "Cesar Actualizado",
  "apellido": "Ramírez Actualizado",
  "telefono": "123456789",
  "email": "nuevoemail@gmail.com"
}

### DELETE Eliminar un Administrador
DELETE http://localhost:3000/api/administradores/{{id}}
