### GET all items

GET http://localhost:3000/api/items HTTP/1.1


### POST a item

# @name createItem

POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pista de Autos",
    "descripcion": "Pista para autos con curvas y elevaciones.",
    "precio": 29.99,
    "marca": "TrackMasters",
    "cant_vendidos": 250,
    "estado": "Activo",
    "stock": 100,
    "categoria": 1,
    "fotos": [ "https://i.imgur.com/Byi3gBg.jpeg" ]
}


### ID

@id = {{createItem.response.body.data.id}}


### GET one item

GET http://localhost:3000/api/items/{{id}} HTTP/1.1


### PATCH a item

PATCH http://localhost:3000/api/items/{{id}} HTTP/1.1
Content-Type: application/json

{
    // foto?
    "precio": 25,
    "cantVendidos": 300,
    "stock": 50
}


### POST a item

POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "nombre": "Sombrero",
    "descripcion": "Sombrero de mago",
    "precio": 25,
    "marca": "Magic",
    "cant_vendidos": 10,
    "estado": "Activo",
    "stock": 45,
    "categoria": 1,
    "fotos": [ "https://i.imgur.com/Byi3gBg.jpeg" ]
}


### POST a item

# @name createItemToDelete

POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "nombre": "Tijera",
    // foto?
    "descripcion": "",
    "precio": 25,
    "marca": "Modul",
    "cantVendidos": 100,
    "estado": 10,
    "stock": 90,
    "categoria": 2
}


### DELETE a item

@idToDelete = {{createItemToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/characters/{{idToDelete}} HTTP/1.1


### PATCH a item

PATCH http://localhost:3000/api/items/{{idToDelete}} HTTP/1.1
Content-Type: application/json

{
    // foto?
    "precio": 25,
    "cantVendidos": 100,
    "stock": 20
}


### DELETE a item

DELETE http://localhost:3000/api/items/{{idToDelete}} HTTP/1.1


### SEARCH

GET http://localhost:3000/api/items/search?query=Bloques HTTP/1.1
