### 1. LOGIN DE ADMIN (Creado por el Seed)
# @name loginRequest
POST http://localhost:3000/api/admins/login
Content-Type: application/json

{
  "identifier": "admin", 
  "password": "admin123"
}

### 2. CREAR CATEGORÍA (Usa el token del paso 1 automáticamente)
@authToken = {{loginRequest.response.body.token}}

### GET ALL
GET http://localhost:3000/api/categories HTTP/1.1


### POST (Crear Juguetería)
# @name createCategory
POST http://localhost:3000/api/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Amplia variedad de juguetes y juegos educativos.",
  "state": "Inactivo",
  "name": "Juguetería"
}


### VARIABLE (Guardamos el nombre, que es la nueva PK)
@categoryName = {{createCategory.response.body.data.name}}


### GET ONE (Usando la variable)
GET http://localhost:3000/api/categories/{{categoryName}} HTTP/1.1


### PATCH (Modificar Juguetería)
PATCH http://localhost:3000/api/categories/{{categoryName}} HTTP/1.1
Content-Type: application/json

{
  "state": "Activo"
}


### POST2 (Crear Librería)
POST http://localhost:3000/api/categories HTTP/1.1
Content-Type: application/json

{
  "description": "Artículos de librería y papelería.",
  "state": "Activo",
  "name": "Librería"
}


### POST3 (Crear Computación)
POST http://localhost:3000/api/categories HTTP/1.1
Content-Type: application/json

{
  "description": "Artículos de computación e insumos.",
  "state": "Activo",
  "name": "Computacion"
}


### POST Category TO DELETE (Crea Cotillón para borrarlo luego)
# @name createCategoryToDelete
POST http://localhost:3000/api/categories HTTP/1.1
Content-Type: application/json

{
  "description": "Artículos festivos y decorativos.",
  "state": "Activo",
  "name": "Cotillon" 
}


### DELETE (Borrar Cotillón automáticamente)
@nameToDelete = {{createCategoryToDelete.response.body.data.name}}
DELETE http://localhost:3000/api/categories/{{nameToDelete}} HTTP/1.1


### DELETE
DELETE http://localhost:3000/api/categories/Librería HTTP/1.1


### SEARCH
GET http://localhost:3000/api/categories/search?query=Librería HTTP/1.1