### GET all items

GET http://localhost:3000/api/items HTTP/1.1


### POST a item

# @name createItem

POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "name": "Pista de Autos",
    "description": "Pista para autos con curvas y elevaciones.",
    "price": 29.99,
    "brand": "TrackMasters",
    "number_sold": 250,
    "state": "Activo",
    "stock": 100,
    "category": 1,
    "photos": [ "https://i.imgur.com/Byi3gBg.jpeg" ]
}


### ID

@id = {{createItem.response.body.data.id}}


### GET one item

GET http://localhost:3000/api/items/{{id}} HTTP/1.1


### PATCH a item

PATCH http://localhost:3000/api/items/{{id}} HTTP/1.1
Content-Type: application/json

{
    // foto?
    "price": 25,
    "number_sold": 300,
    "stock": 50
}


### POST a item

POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "name": "Sombrero",
    "description": "Sombrero de mago",
    "price": 25,
    "brand": "Magic",
    "number_sold": 10,
    "state": "Activo",
    "stock": 45,
    "category": 1,
    "photos": [ "https://i.imgur.com/Byi3gBg.jpeg" ]
}


### POST a item

# @name createItemToDelete

POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "name": "Tijera",
    // foto?
    "description": "",
    "price": 25,
    "brand": "Modul",
    "number_sold": 100,
    "state": 10,
    "stock": 90,
    "category": 2
}


### DELETE a item

@idToDelete = {{createItemToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/items/{{idToDelete}} HTTP/1.1


### PATCH a item

PATCH http://localhost:3000/api/items/{{idToDelete}} HTTP/1.1
Content-Type: application/json

{
    // foto?
    "price": 25,
    "number_sold": 100,
    "stock": 20
}


### DELETE a item

DELETE http://localhost:3000/api/items/{{idToDelete}} HTTP/1.1


### SEARCH

GET http://localhost:3000/api/items/search?query=Bloques HTTP/1.1
