### GET ALL Administradores
GET http://localhost:3000/api/admins

### POST Crear un Administrador
# @name createAdmin
POST http://localhost:3000/api/admins
Content-Type: application/json

{
  "name": "AdminSeguro",
  "last_name": "Ramírez",
  "phone": "423423423",
  "user": "admin1",
  "password": "12345",
  "email": "admin1@gmail.com"
}

### POST Iniciar Sesión (Login)
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "identifier": "admin1",
  "password": "password123"
}

### ID del Administrador creado
@id = {{createAdmin.response.body.data.id}}

### GET Un Administrador por ID
GET http://localhost:3000/api/admins/{{id}}

### PATCH Actualizar un Administrador
PATCH http://localhost:3000/api/admins/{{id}}
Content-Type: application/json

{
  "name": "Cesar Actualizado",
  "last_name": "Ramírez Actualizado",
  "phone": "123456789",
  "email": "nuevoemail@gmail.com"
}

### DELETE Eliminar un Administrador
DELETE http://localhost:3000/api/admins/{{id}}
