### GET ALL

GET http://localhost:3000/api/categorias HTTP/1.1


### POST

# @name createCategoria

POST http://localhost:3000/api/categorias HTTP/1.1
Content-Type: application/json

{
  "descripcion": "Amplia variedad de juguetes y juegos educativos para niños de todas las edades.",
  "estado": "Inactivo",
  "nombre": "Juguetería"
}


### ID

@id = {{createCategoria.response.body.data.id}}


### GET ONE

GET http://localhost:3000/api/categorias/{{id}} HTTP/1.1


### PATCH

PATCH http://localhost:3000/api/categorias/{{id}} HTTP/1.1
Content-Type: application/json

{
  "estado": "Inactivo"
}


### POST2

POST http://localhost:3000/api/categorias HTTP/1.1
Content-Type: application/json

{
  "descripcion": "Artículos de librería, materiales de estudio y artículos de papelería para todas las necesidades.",
  "estado": "Activo",
  "nombre": "Librería"
}


### POST3

POST http://localhost:3000/api/categorias HTTP/1.1
Content-Type: application/json

{
  "descripcion": "articulos de computacion",
  "estado": "Activo",
  "nombre": "Computacion"
}


### POST Categoría TO DELETE

# @name createCategoriaToDelete

POST http://localhost:3000/api/categorias HTTP/1.1
Content-Type: application/json

{
  "descripcion": "Artículos festivos y decorativos para todo tipo de celebraciones, desde cumpleaños hasta eventos temáticos.",
  "estado": "Activo",
  "nombre": "Computacion"
}


### DELETE

@idToDelete = {{createCategoriaToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/categorias/{{idToDelete}} HTTP/1.1


### DELETE WITH MANUAL ID

DELETE http://localhost:3000/api/categorias/9 HTTP/1.1


### SEARCH

GET http://localhost:3000/api/categorias/search?query=Librería HTTP/1.1
